services:
  backend:
    image: bardinpetr/itmo_is_lab_1:latest
    build: ../
    restart: always
    depends_on:
      - pg
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/medical
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  pg:
    image: postgres:17-alpine
    volumes:
      - ./.tmp/pg:/data
    environment:
      POSTGRES_DB: medical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  frontend:
    image: bardinpetr/itmo_is_lab_1_client:latest
    restart: always

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "18888:80"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "11883:1883"
      - "9001:9001"
    volumes:
      - ./config/mqtt:/mosquitto/config:ro
