services:
  backend:
    image: bardinpetr/itmo_med_delivery_backend:latest
    build: ../
    restart: always
    depends_on:
      - pg
      - mqtt
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/medical
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_MQTT_HOST: mqtt
      APP_MQTT_PORT: 1883

  pg:
    image: postgres:17-alpine
    volumes:
      - ./.tmp/pg:/data
    environment:
      POSTGRES_DB: medical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  frontend:
    image: bardinpetr/itmo_med_delivery_frontend:latest
    build:
      context: ../../medicine-drone-delivery-client
    restart: always

  nginx:
    image: nginx
    restart: always
    depends_on:
      - backend
      - frontend
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4200:80"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "11883:1883"
      - "9001:9001"
    volumes:
      - ./config/mqtt:/mosquitto/config:ro
