services:
  backend:
    image: bardinpetr/itmo_is_lab_1:latest
    build: ../
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/studs
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: s367079

  pg:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: medical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  frontend:
    image: bardinpetr/itmo_is_lab_1_client:latest
    restart: always
    ports:
      - "8081:80"

  #  nginx:
  #    image: nginx
  #    restart: always
  #    volumes:
  #      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #    ports:
  #      - "18888:80"

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    network_mode: host

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1885:1883"
      - "9001:9001"
    volumes:
      - ./mqconfig:/mosquitto/config:rw
      - ./mqdata:/mosquitto/data:rw
      - ./mqlog:/mosquitto/log:rw
